BookClub.create(:title => "April & Oliver", :author => "Tess Callahan",  :isbn => "9780446540599") 
BookClub.create(:title => "Breakfast at Sally's", :author => "Richard LeMieux",  :isbn => "9781602392939") 
BookClub.create(:title => "Charms for the Easy Life", :author => "Kaye Gibbons",  :isbn => "0380722704") 
BookClub.create(:title => "I am Nujood, Age 10 and Divorced", :author => "Nujood Ali",  :isbn => "9780307589675") 
BookClub.create(:title => "In the Sanctuary of Outcasts", :author => "Neil Young",  :isbn => "9780061351600") 
BookClub.create(:title => "Loving Frank",  :sub_title => "A Novel", :author => "Nancy Horan",  :isbn => "9780345494993") 
BookClub.create(:title => "My Sister's Keeper",  :sub_title => "A Novel", :author => "Jodi Picoult",  :isbn => "0743454529") 
BookClub.create(:title => "Of Beetles and Angels", :author => "Mawi Asgedom",  :isbn => "0970498268") 
BookClub.create(:title => "Shadow divers",  :sub_title => "the true adventure of two Americans who risked everything to solve one of the last mysteries of World War II", :author => "Robert Kurson",  :isbn => "0375508589") 
BookClub.create(:title => "The Alchemist",  :sub_title => "A Fable About Following Your Dream", :author => "Paulo Coelho",  :isbn => "9780062502179") 
BookClub.create(:title => "The Elegance of the Hedgehog", :author => "Muriel Barbery",  :isbn => "9781933372600") 
BookClub.create(:title => "The Glass Castle", :author => "Jeannette Walls",  :isbn => "0743247531") 
BookClub.create(:title => "The Guernsey Literary and Potato Peel Pie Society", :author => "Mary Ann Shaffer & Annie Barrows",  :isbn => "9780385340991") 
BookClub.create(:title => "The Last Lecture", :author => "Randy Pausch",  :isbn => "9781401323257") 
BookClub.create(:title => "The Memory Keeper's Daughter", :author => "Kim Edwards",  :isbn => "0670034169") 
BookClub.create(:title => "The No. 1 Ladies' Detective Agency", :author => "Alexander McCall Smith",  :isbn => "1400031346") 
BookClub.create(:title => "The Player", :author => "Michael Tolkin",  :isbn => "0679722548") 
BookClub.create(:title => "The Road", :author => "Cormac McCarthy",  :isbn => "9780307476302") 
BookClub.create(:title => "The Screwtape Letters",  :sub_title => "with, Screwtape Proposes a Toast", :author => "C. S. Lewis",  :isbn => "0060652896") 
BookClub.create(:title => "The Shack", :author => "William P. Young",  :isbn => "9780964729230") 
BookClub.create(:title => "The Story of Edgar Sawtelle",  :sub_title => "a novel", :author => "David Wroblewski",  :isbn => "9780061374227") 
BookClub.create(:title => "The Thirteenth Tale",  :sub_title => "a novel", :author => "Diane Setterfield",  :isbn => "0743298020") 
BookClub.create(:title => "The Uncommon Reader",  :sub_title => "a novella", :author => "Alan Bennett",  :isbn => "9780374280963") 
BookClub.create(:title => "Three Cups of Tea",  :sub_title => "one man's mission to fight terrorism and build nations' one school at a time", :author => "Greg Mortenson and David Oliver Relin",  :isbn => "0670034827") 
BookClub.create(:title => "Water for Elephants",  :sub_title => "a novel", :author => "Sara Gruen",  :isbn => "1565124995") 
BookClub.create(:title => "When Will There Be Good News?", :author => "Kate Atkinson",  :isbn => "9780316154857") 
BookClub.create(:title => "Women of the Silk", :author => "Gail Tsukiyama",  :isbn => "0312099436")
Patron.create(:library_card => "21257004005162", :first_name =>"Felipe", :last_name =>"Dominguez", :contact_phone =>"888-923-3406", :contact_email =>"fez@dom.com")
Patron.create(:library_card => "21257123456789", :first_name =>"Numuero", :last_name =>"Uno", :contact_phone =>"1238-4563-78906", :contact_email =>"onetwothree@digits.com")
